const DEFAULT_WORKSHOP_LAYOUT = {
  version: 1,
  canvas: {
    width: 1200,
    height: 760,
  },
  pages: {
    home: {
      items: [
        {
          id: "topbar",
          kind: "nav",
          label: "Top Navigation",
          description: "Logo, global navigation and quick actions.",
          x: 4,
          y: 4,
          w: 92,
          h: 10,
          z: 1,
          visible: true,
        },
        {
          id: "hero",
          kind: "hero",
          label: "Hero Spotlight",
          description: "Primary heading, pitch text and call-to-action.",
          x: 4,
          y: 18,
          w: 58,
          h: 24,
          z: 2,
          visible: true,
        },
        {
          id: "socialProof",
          kind: "stats",
          label: "Social Proof",
          description: "Quick metrics, trust badges or top stats.",
          x: 66,
          y: 18,
          w: 30,
          h: 24,
          z: 3,
          visible: true,
        },
        {
          id: "feed",
          kind: "feed",
          label: "Idea Feed",
          description: "Main feed, cards and sorting controls.",
          x: 4,
          y: 46,
          w: 58,
          h: 40,
          z: 4,
          visible: true,
        },
        {
          id: "insightRail",
          kind: "sidebar",
          label: "Insight Rail",
          description: "Secondary widgets, filters or profile summary.",
          x: 66,
          y: 46,
          w: 30,
          h: 18,
          z: 5,
          visible: true,
        },
        {
          id: "trendPanel",
          kind: "panel",
          label: "Trend Panel",
          description: "Hot tags, charts or recommended entries.",
          x: 66,
          y: 68,
          w: 30,
          h: 18,
          z: 6,
          visible: true,
        },
        {
          id: "footer",
          kind: "footer",
          label: "Footer",
          description: "Links, legal copy and utility actions.",
          x: 4,
          y: 90,
          w: 92,
          h: 6,
          z: 7,
          visible: true,
        },
      ],
    },
  },
};

module.exports = { DEFAULT_WORKSHOP_LAYOUT };