module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  OTP_RESEND_COOLDOWN: "OTP_RESEND_COOLDOWN",
  COMMENT_COOLDOWN: "COMMENT_COOLDOWN",
  FEEDBACK_VALIDATION_FAILED: "FEEDBACK_VALIDATION_FAILED",
  INVALID_ID: "INVALID_ID",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  DUPLICATE: "DUPLICATE",
  SERVER_ERROR: "SERVER_ERROR",
  PUBLIC_LIMIT_EXCEEDED: "PUBLIC_LIMIT_EXCEEDED",
  OAUTH_NOT_LINKED: "OAUTH_NOT_LINKED",
  OAUTH_UNLINK_LAST_METHOD: "OAUTH_UNLINK_LAST_METHOD",
  // 账号被平台封禁（403）。★ 与 UNAUTHORIZED(401) 分开：客户端对 401 的处置是
  // 「登出重登」，而封禁重登也没用 —— 客户端要按这个码把 message 里的原因展示出来。
  BANNED: "BANNED",
  PASSWORD_ALREADY_SET: "PASSWORD_ALREADY_SET",
  PASSWORD_NOT_SET: "PASSWORD_NOT_SET",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
};
