module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  OTP_RESEND_COOLDOWN: "OTP_RESEND_COOLDOWN",
  INVALID_ID: "INVALID_ID",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  DUPLICATE: "DUPLICATE",
  SERVER_ERROR: "SERVER_ERROR",
  PUBLIC_LIMIT_EXCEEDED: "PUBLIC_LIMIT_EXCEEDED",
};
